main: me.creepinson.plugin.Main
name: DeathClock
author: IK_Knight, ElgarL
version: 1.0.1
commands:
    status:
        description: checks if plugin is sober or not
    time:
        description: checks how much time you have


# MAD THANKS TO ELGARL!!!!