main: me.creepinson.plugin.Main
name: DeathClock
author: IK_Knight
version: 1.0.0
commands:
    status:
        description: checks if plugin is sober or not
# THANK YOU CREEPINSON FOR THE FREE CODE
#+15 social credit
# © your mom