main: me.creepinson.plugin.Main
name: DeathClock
author: IK_Knight, ElgarL
version: 1.0.1
api-version: 1.19
commands:
  status:
    description: checks if plugin is sober or not
    usage: /<command>
  time:
    description: checks how much time you have
    usage: /<command>
  givetime:
    description: gives time to a player, from your time
    usage: /<command> <player> <time>


# MAD THANKS TO ELGARL!!!!